### PR TITLE
FIX #217: Quote string contains line separator under STRICT_CHECK_FOR_QUOTING mode

### LINKED ISSUE #217: CSV: Should quote strings with line separator under STRICT_CHECK_FOR_QUOTING mode
When string data with line separator is serialized to csv, it shold be quoted, shouldn't it?
But it actually is NOT quoted if `CsvGenerator.Feature.STRICT_CHECK_FOR_QUOTING` is enabled.

Test below is failed:

```java
public void testExplicitWithLineSeparator() throws Exception
{
    CsvSchema schema = CsvSchema.emptySchema();
    ObjectWriter writer =  new CsvMapper().writer(schema)
            .with(CsvGenerator.Feature.STRICT_CHECK_FOR_QUOTING);

    String csv =writer.writeValueAsString(new Object[]{"abc", "de\nf", "ghi"});
    assertEquals("abc,\"de\nf\",ghi\n", csv);  // FAILED!
}
```

```
expected:<abc,["de
f"],ghi
> but was:<abc,[de
f],ghi
>
```

version:  v.2.11.2 and currrent master branch

### PR DESCRIPTION
**Pull request by wkwkhautbois**
fix #217 

This is my first pull request to Jackson project. If I made mistakes, please tell me. I will fix them.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Thank you for submitting this! I'll need to read this with thought -- thank you for adding tests, I may start looking at that and think about implementation (mostly wrt performance aspects).

**Comment by wkwkhautbois** [comment]
Thank you!
I modified this pull request for better performance, but stil need your review.


I also tried performance testing in my local environment.
I cloned https://github.com/FasterXML/jackson-benchmarks and ran csv writing test as

```
java -Xmx256m -jar target/microbenchmarks.jar ".*CsvStdWrite.*PojoMediaItem.*" -wi 4 -i 5 -f 9 -t 1
```


Current 2.11 branch

```
Benchmark                                   Mode  Cnt       Score      Error  Units
CsvStdWriteAfterburner.writePojoMediaItem  thrpt   45  705641.648 ± 5888.382  ops/s
CsvStdWriteVanilla.writePojoMediaItem      thrpt   45  652983.512 ± 7363.394  ops/s
```

After applying this pull request

```
Benchmark                                   Mode  Cnt       Score       Error  Units
CsvStdWriteAfterburner.writePojoMediaItem  thrpt   45  704326.206 ± 12776.612  ops/s
CsvStdWriteVanilla.writePojoMediaItem      thrpt   45  658500.498 ±  9367.158  ops/s
```

Environment
Windows 10 (2004)
Ryzen 3400GE (3.30GB)
AdoptOpenJDK 1.8.0_265

**Comment by cowtowncoder** [comment]
Thank you for the updates! I am back to reviewing this PR; apologies for slow follow-up (busy trying to complete 2.12.0-pr1).
I plan to get i

**Comment by cowtowncoder** [comment]
@wkwkhautbois Thank you very much for this fix! You are right in that there is measurable overhead; I realized that additional check only occurs (usually) for relatively few characters due to check for "minSafeChar", calculation of which linefeed is already included.

I ended up merging it manually with minor changes (only need to check the first character of linefeed since all valid linefeeds must contain all of them anyway), so will close this PR -- fix will be in 2.11.3 (and 2.12.0).

**Pull request closed without merging**
