### PR TITLE
Updating Snakeyaml to 1.26

### PR DESCRIPTION
**Pull request by coheigea**

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Thank you!

**Comment by coheigea** [comment]
Could it be cherry-picked back to 2.10 as well? Or do you want me to open a separate PR?

**Comment by cowtowncoder** [comment]
Was curious if 2.11 was intentional to reduce risk. I can merge it to 2.10 if it seems like a low-risk change.

**Comment by cowtowncoder** [comment]
Done.

**Pull request merged**
