### PR TITLE
Use latest SnakeYAML version 1.23 and get rid of deprecated methods

### LINKED ISSUE #81: Jackson 2.9.5, 2.9.6 incompatible with snakeyaml 1.20, 1.21
A backwards-incompatible (with jackson `2.9.5`) change was [introduced](https://bitbucket.org/asomov/snakeyaml/commits/6cb855839ebc1f3796cff26aa6e5423f1395b975) in snakeyaml `1.20`, so anyone trying to use the latest released versions of jackson and snakeyaml would run into a problem:
```
java.lang.NoSuchMethodError: org.yaml.snakeyaml.events.MappingStartEvent.<init>(Ljava/lang/String;Ljava/lang/String;ZLorg/yaml/snakeyaml/error/Mark;Lorg/yaml/snakeyaml/error/Mark;Ljava/lang/Boolean;)V

    at com.fasterxml.jackson.dataformat.yaml.YAMLGenerator.writeStartObject(YAMLGenerator.java:489)
    at com.fasterxml.jackson.core.base.GeneratorBase.writeStartObject(GeneratorBase.java:286)
    at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:626)
    at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
    at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3893)
    at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3207)
```

### PR DESCRIPTION
**Pull request by asomov**
Fix #81 (and #82)

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Ok, based on comments in #81 this makes sense and I can merge this for 2.10 . Merge from 2.10 to master is easy enough too.

Just one question to make sure I understand implications: would the new module work against older snakeYAML versions or not? If we were still shading dependency it would not matter, but unfortunately this is not done (due to complications with OSGi use case, long story).

If there are specific limitations (will work for a range of versions) that may be fine, but we need to document those.

**Comment by asomov** [comment]
The new code will work with 1.23 onwards. Older versions are not supported.
(We will do our best to keep the backwards compatibility)

If this is merged to master than the pull request for master can be cancelled.

**Comment by cowtowncoder** [comment]
@asomov  I'll try to play a bit with this -- perhaps I misunderstand compatibility issue tho.
Maybe it's that new version would work with old code, so that 2.9 can upgrade to 1.23; and then 2.10 can upgrade to use new config? 

If so, that's fine. But 2.9 and 2.10 have bit different requirements.

**Comment by cowtowncoder** [comment]
Yes, looks like 1.22 and 1.23 have re-added temporarily missing method, and will "just work" as expected.
I will now merge this for 2.10 to upgrade API usage.

**Comment by asomov** [comment]
I also might misunderstand the issue. Yes, we have added back the missing methods.

I created 3 pull requests which do the same. Upgrade the SnakeYAML version to 1.23

If the commits from 2.9 go to 2.10 and than further to master than you need to merge only one  (for 2.9)

**Comment by asomov** [comment]
Should I close the pull request for master ?

(if you merge everything to master from 2.10)

**Comment by asomov** [comment]
thank you

**Pull request merged**
