### PR TITLE
Fix Jackson reference

### PR DESCRIPTION
**Pull request by WilderPereira**

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Not quite sure what the fix here would be... relative reference resolves to the same as proposed change?

**Comment by WilderPereira** [comment]
No, it doesn't. It is currently resolving to https://github.com/FasterXML/jackson-dataformats-text/jackson

**Comment by cowtowncoder** [comment]
Ah. My mistake: was looking at main-level README, not csv one.

**Comment by cowtowncoder** [comment]
Thanks!

**Pull request merged**
