### PR TITLE
SnakeYAML Engine

### PR DESCRIPTION
**Pull request by asomov**
Hi all,
finally the [SnakeYAML Engine](https://bitbucket.org/asomov/snakeyaml-engine) has been released.
It is a re-build of SnakeYAML which supports YAML 1.2 (superset of JSON)

This pull request introduces SnakeYAML Engine and makes jackson 'YAML 1.2 complaint'.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
@asomov Apologies for missing this one. I'll see if I can manually merge this in `master` for 3.0 (looks like Java 8 is required)

**Comment by asomov** [comment]
I will check the merge conflicts.

(Yes, it is a re-write of SnakeYAML which supports YAML 1.2)

**Comment by asomov** [comment]
The merge conflicts were resolved.

**Comment by cowtowncoder** [comment]
@asomov excellent, thank you!

**Pull request merged**
