### PR TITLE
Add failing test for #400 (yaml, char decoding)

### PR DESCRIPTION
**Pull request by cowtowncoder**
Reproduction of issue #400 found by OSS-Fuzz.

### CODE REVIEW

**Comment by asomov** [comment]
@cowtowncoder feel free either to provide more info or file an issue in snakeyaml bug tracker
I did not quite catch what is the YAML which fails

**Comment by cowtowncoder** [comment]
@asomov Np, sorry I should have included reproduction input right here. Thank you for super-fast follow up!

**Comment by asomov** [comment]
@cowtowncoder fixed
https://bitbucket.org/snakeyaml/snakeyaml/issues/576

**Comment by cowtowncoder** [comment]
Excellent. Thank you @asomov !

**Comment by asomov** [comment]
@cowtowncoder sorry, the issue tracker is temp closed because of the spam attack. But it is fixed and it will be delivered in version 2.1

**Comment by cowtowncoder** [comment]
@asomov Sounds good -- looking forward to 2.1 release!

**Pull request merged**
